export const UPDATE_PAGE = "UPDATE_PAGE"

export const GET_CHARACTERS = "GET_CHARACTERS"
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS"
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR"

export const REMOVE_CHARACTER = "REMOVE_CHARACTER"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"

export const GET_FAVS = "GET_FAVS"
export const GET_FAVS_SUCCESS = "GET_FAVS_SUCCESS"
export const GET_FAVS_ERROR = "GET_FAVS_ERROR"